site_name: NeuroPy Seminar
site_url: https://arashshahidi1997.github.io/NeuroPySeminar/
repo_url: https://github.com/arashshahidi1997/NeuroPySeminar

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - navigation.indexes      # ðŸ‘ˆ enables section landing pages
    - content.code.copy

plugins:
  - search
  - roamlinks

markdown_extensions:
  - admonition
  - tables
  - footnotes
  - toc:
      permalink: true

docs_dir: docs
site_dir: site

nav:
  - Registration: register.md
  - Home: index.md
  - Tools:
      - index: tools/index.md        # ðŸ‘ˆ landing page for Tools tab
      - Rescheduler: tools/Reschedule.html
      - Paper Pool: tools/PaperPool.html
      - Method Picker: tools/MethodPicker.html
      - SSH Setup: tools/SSHSetup.html

# Added by script: Announcements tab
  - Announcements:
      - index: announcements/index.md
      - Apply Flyer: announcements/apply-flyer.html

# Added by script: Schedule tab
  - Schedule:
      - index: schedule/index.md
      - Semester Schedule: schedule/SemesterSchedule.html
      - Weekly Schedule: schedule/WeeklySchedule.html
      - Google Calendar: https://calendar.google.com/calendar/u/0/r?cid=NGFhNzU5NWVhYmU4MTAzNzFmZTkwMTNkYzVkMDZmY2Y1NGI5MDU2ZGViMTk5NDAwMjVjMmQzODdkYTg2MmVmY0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t

  - Slides:
      - index: slides/index.md        # ðŸ‘ˆ landing page for Slides tab
      - BootcampI: slides/bootcamp/index.html
      - BootcampII: slides/bootcamp-ii/index.html
      - Autoregressive: slides/autoregressive/index.html
      - Multitaper: slides/multitaper/index.html
      - VSCode: slides/vscode-setup/index.html
      - Snakemake: slides/snakemake/index.html
      - Datalad: slides/datalad/index.html
      - BIDS: slides/bids/index.html
      - sirocampus: slides/sirocampus/index.html
      - Holoviews: slides/holoviews/index.html
      - GPFA: slides/gpfa/index.html
      - HMM: slides/hmm/index.html
      - CCA: slides/cca/index.html
